### ISSUE TITLE
Compatibility with WSL (Ubuntu 16 Bash on Windows 10)

### ISSUE THREAD

**Issue by rainabba** [davidmarkclements/0x#68] opened 2017-04-25 23:04 UTC
I realize this is likely out of your control, but I wanted to mention it just in case it wasn't and so I can reference this with MS WSL Support (they're quite responsive) in case this is something they'll have to address.

Getting pef installed was a bit of a challenge and ultimately I had to download 2.1GB of linux source, then do a `make` on `linux/tools/perf` and `cp perf /usr/bin/` manually. Once that was done, I was able to install and try to use 0x, but I hit the following (running `0x split.js`):

> perf_event_open(..., 0) failed unexpectedly with error 22 (Invalid argument)
> Error:
> The sys_perf_event_open() syscall returned with 22 (Invalid argument) for event (cpu-clock).
> /bin/dmesg may provide additional information.
> No CONFIG_PERF_EVENTS=y kernel support configured?

**Comment by mcollina** [comment] 2017-08-07 15:45
I do not think perf is supported on WSL. I have some rough implementation of some tooling for Windows, but I haven't been able to finish it, as I am stuck in resolving the symbols.

**Comment by mcollina** [comment] 2017-08-07 15:46
I'm closing this, as the problem is not really on us.

**Closed by mcollina** 2017-08-07 15:46 UTC
