### ISSUE TITLE
🐞 Cannot read property 'toString' of undefined (from src.toString())

### ISSUE THREAD

**Issue by glenjamin** [davidmarkclements/0x#27] opened 2016-04-02 15:41 UTC
Just received the following error trying this out, on OS X 10.11.3

```
> npm version
{ 'devboard-example': '1.0.0',
  npm: '3.8.5',
  ares: '1.10.1-DEV',
  http_parser: '2.5.2',
  icu: '56.1',
  modules: '46',
  node: '4.4.2',
  openssl: '1.0.2g',
  uv: '1.8.0',
  v8: '4.5.103.35',
  zlib: '1.2.8' }

> npm ls -g 0x
/usr/local/lib
└── 0x@2.2.6
```

```
/usr/local/lib/node_modules/0x/index.js:122
      throw e
      ^

TypeError: Cannot read property 'toString' of undefined
    at Readable.<anonymous> (/usr/local/lib/node_modules/0x/index.js:325:22)
    at emitOne (events.js:77:13)
    at Readable.emit (events.js:169:7)
    at Labeled.<anonymous> (/usr/local/lib/node_modules/0x/node_modules/read-only-stream/index.js:28:44)
    at emitOne (events.js:77:13)
    at Labeled.emit (events.js:169:7)
    at Labeled.<anonymous> (/usr/local/lib/node_modules/0x/node_modules/stream-splicer/index.js:130:18)
    at emitOne (events.js:82:20)
    at Labeled.emit (events.js:169:7)
    at DestroyableTransform.<anonymous> (/usr/local/lib/node_modules/0x/node_modules/stream-splicer/index.js:130:18)
```

**Comment by eljefedelrodeodeljefe** [comment] 2016-04-02 18:30
What kind if script have you been running? Anything special?

**Comment by eljefedelrodeodeljefe** [comment] 2016-04-02 18:36
hmm. This has something todo with `clean-browserify-string` can you run the same command with `DEBUG=0x [here come command]` and copy-paste the error message?

**Comment by mcollina** [comment] 2016-04-03 10:35
Can you please isolate/upload a script that it is causing this error?

**Comment by glenjamin** [comment] 2016-04-03 10:48
Ah, `DEBUG` seems to have helped:

The code isn't particularly isolated, but it is available at https://github.com/glenjamin/devboard/blob/master/example/

```
> DEBUG=0x BABEL_ENV=production 0x node ./node_modules/.bin/kotatsu build client -o public/build --public public/ --index public/index.html --devtool \#cheap-source-map --babel --config webpack.config.js main.js --no-progress
0x captures stacks using dtrace, which requires sudo access
Password:

Profiling[kotatsu] (v0.9.1)
[kotatsu] Compiling...
[kotatsu] Built in 4.5s.
[kotatsu] Done!
  0x begin rendering +0ms
  0x converted stacks to intermediate format +16s
  0x Unable to generate client side code for flamegraph +2s { [RangeError: Maximum call stack size exceeded]
  undefined: true,
  stream:
   Labeled {
     _readableState:
      ReadableState {
        objectMode: true,
        highWaterMark: 16,
        buffer: [],
        length: 0,
        pipes: [Object],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: true,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events:
      { end: [Object],
        finish: [Object],
        error: [Object],
        data: [Function: ondata],
        _mutate: [Object] },
     _eventsCount: 5,
     _maxListeners: undefined,
     _writableState:
      WritableState {
        objectMode: true,
        highWaterMark: 16,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 1,
        writing: true,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: [Function: nop],
        writelen: 1,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 3,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     allowHalfOpen: true,
     _options: { objectMode: true },
     _wrapOptions: { objectMode: true },
     _streams: [ [Object] ],
     length: 1,
     label: 'syntax' } }
/usr/local/lib/node_modules/0x/index.js:122
      throw e
      ^

TypeError: Cannot read property 'toString' of undefined
    at Readable.<anonymous> (/usr/local/lib/node_modules/0x/index.js:325:22)
    at emitOne (events.js:90:13)
    at Readable.emit (events.js:182:7)
    at Labeled.<anonymous> (/usr/local/lib/node_modules/0x/node_modules/read-only-stream/index.js:28:44)
    at emitOne (events.js:90:13)
    at Labeled.emit (events.js:182:7)
    at Labeled.<anonymous> (/usr/local/lib/node_modules/0x/node_modules/stream-splicer/index.js:130:18)
    at emitOne (events.js:95:20)
    at Labeled.emit (events.js:182:7)
    at DestroyableTransform.<anonymous> (/usr/local/lib/node_modules/0x/node_modules/stream-splicer/index.js:130:18)
```

**Comment by davidmarkclements** [comment] 2016-04-05 11:04
hey @glenjamin are you on linux or OS X?

**Comment by glenjamin** [comment] 2016-04-05 11:10
On `OS X 10.11.3`

**Comment by davidmarkclements** [comment] 2016-04-05 11:33
ok so @glenjamin the problem is the sample data being collected from this is so big, that's blowing browserify's call stack. 

Here's a quick work around, while we figure out a way to handle this gracefully:

```sh
DEBUG=0x BABEL_ENV=production node --stack-size=8024 $(npm get prefix)/lib/node_modules/0x/cmd.js node ./node_modules/.bin/kotatsu build client -o public/build --public public/ --index public/index.html --devtool \#cheap-source-map --babel --config webpack.config.js main.js --no-progress
```

Don't set stack size to more than 8024, you'll likely get a segfault.

**Comment by davidmarkclements** [comment] 2016-04-05 11:41
ah ho hum - it's also blowing the call stack in the ui - so you can open the flamegraph.html with this command:

```sh
/Applications/Google\ Chrome.app/Contents/MacOS/Googl Chrome --user-data-dir=/tmp/chrome2/ --js-flags="--stack-size 8024" flamegraph.html
```

That will cause it to render. Obviously you'll need 8gb ram spare...

**Comment by davidmarkclements** [comment] 2016-04-05 11:43
You may also want to zoom out one (press the - button) - that's a *LOT* of stacks right there

**Comment by davidmarkclements** [comment] 2016-04-05 11:57
opened new issue for handling this, closing this issue - thanks for highlighting this @glenjamin !

**Closed by davidmarkclements** 2016-04-05 11:57 UTC
